server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_mall?useSSL=false&serverTimezone=UTC
    username: root
    password: www2005A
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campusmall.mall.entity

logging:
  level:
    root: INFO
    com.campusmall.mall: DEBUG
